elementos = [
    {"simbolo": "H", "nome": "Hidrogênio", "numero_atomico": 1, "massa_atomica": 1.008},
    {"simbolo": "He", "nome": "Hélio", "numero_atomico": 2, "massa_atomica": 4.0026},
    {"simbolo": "Li", "nome": "Lítio", "numero_atomico": 3, "massa_atomica": 6.94},
    {"simbolo": "Be", "nome": "Berílio", "numero_atomico": 4, "massa_atomica": 9.0122},
    {"simbolo": "B", "nome": "Boro", "numero_atomico": 5, "massa_atomica": 10.81},
    {"simbolo": "C", "nome": "Carbono", "numero_atomico": 6, "massa_atomica": 12.011},
    {"simbolo": "N", "nome": "Nitrogênio", "numero_atomico": 7, "massa_atomica": 14.007},
    {"simbolo": "O", "nome": "Oxigênio", "numero_atomico": 8, "massa_atomica": 15.999},
    {"simbolo": "F", "nome": "Flúor", "numero_atomico": 9, "massa_atomica": 18.998},
    {"simbolo": "Ne", "nome": "Neônio", "numero_atomico": 10, "massa_atomica": 20.180},
    {"simbolo": "Na", "nome": "Sódio", "numero_atomico": 11, "massa_atomica": 22.990},
    {"simbolo": "Mg", "nome": "Magnésio", "numero_atomico": 12, "massa_atomica": 24.305},
    {"simbolo": "Al", "nome": "Alumínio", "numero_atomico": 13, "massa_atomica": 26.982},
    {"simbolo": "Si", "nome": "Silício", "numero_atomico": 14, "massa_atomica": 28.085},
    {"simbolo": "P", "nome": "Fósforo", "numero_atomico": 15, "massa_atomica": 30.974},
    {"simbolo": "S", "nome": "Enxofre", "numero_atomico": 16, "massa_atomica": 32.06},
    {"simbolo": "Cl", "nome": "Cloro", "numero_atomico": 17, "massa_atomica": 35.45},
    {"simbolo": "Ar", "nome": "Argônio", "numero_atomico": 18, "massa_atomica": 39.948},
    {"simbolo": "K", "nome": "Potássio", "numero_atomico": 19, "massa_atomica": 39.098},
    {"simbolo": "Ca", "nome": "Cálcio", "numero_atomico": 20, "massa_atomica": 40.078},
    {"simbolo": "Sc", "nome": "Escândio", "numero_atomico": 21, "massa_atomica": 44.956},
    {"simbolo": "Ti", "nome": "Titânio", "numero_atomico": 22, "massa_atomica": 47.867},
    {"simbolo": "V", "nome": "Vanádio", "numero_atomico": 23, "massa_atomica": 50.942},
    {"simbolo": "Cr", "nome": "Cromo", "numero_atomico": 24, "massa_atomica": 51.996},
    {"simbolo": "Mn", "nome": "Manganês", "numero_atomico": 25, "massa_atomica": 54.938},
    {"simbolo": "Fe", "nome": "Ferro", "numero_atomico": 26, "massa_atomica": 55.845},
    {"simbolo": "Co", "nome": "Cobalto", "numero_atomico": 27, "massa_atomica": 58.933},
    {"simbolo": "Ni", "nome": "Níquel", "numero_atomico": 28, "massa_atomica": 58.693},
    {"simbolo": "Cu", "nome": "Cobre", "numero_atomico": 29, "massa_atomica": 63.546},
    {"simbolo": "Zn", "nome": "Zinco", "numero_atomico": 30, "massa_atomica": 65.38},
    {"simbolo": "Ga", "nome": "Gálio", "numero_atomico": 31, "massa_atomica": 69.723},
    {"simbolo": "Ge", "nome": "Germânio", "numero_atomico": 32, "massa_atomica": 72.63},
    {"simbolo": "As", "nome": "Arsênio", "numero_atomico": 33, "massa_atomica": 74.922},
    {"simbolo": "Se", "nome": "Selênio", "numero_atomico": 34, "massa_atomica": 78.971},
    {"simbolo": "Br", "nome": "Bromo", "numero_atomico": 35, "massa_atomica": 79.904},
    {"simbolo": "Kr", "nome": "Criptônio", "numero_atomico": 36, "massa_atomica": 83.798},
    {"simbolo": "Rb", "nome": "Rubídio", "numero_atomico": 37, "massa_atomica": 85.468},
    {"simbolo": "Sr", "nome": "Estrôncio", "numero_atomico": 38, "massa_atomica": 87.62},
    {"simbolo": "Y", "nome": "Ítrio", "numero_atomico": 39, "massa_atomica": 88.906},
    {"simbolo": "Zr", "nome": "Zircônio", "numero_atomico": 40, "massa_atomica": 91.224},
    {"simbolo": "Nb", "nome": "Nióbio", "numero_atomico": 41, "massa_atomica": 92.906},
    {"simbolo": "Mo", "nome": "Molibdênio", "numero_atomico": 42, "massa_atomica": 95.95},
    {"simbolo": "Tc", "nome": "Tecnécio", "numero_atomico": 43, "massa_atomica": 98},
    {"simbolo": "Ru", "nome": "Rutênio", "numero_atomico": 44, "massa_atomica": 101.07},
    {"simbolo": "Rh", "nome": "Ródio", "numero_atomico": 45, "massa_atomica": 102.91},
    {"simbolo": "Pd", "nome": "Paládio", "numero_atomico": 46, "massa_atomica": 106.42},
    {"simbolo": "Ag", "nome": "Prata", "numero_atomico": 47, "massa_atomica": 107.87},
    {"simbolo": "Cd", "nome": "Cádmio", "numero_atomico": 48, "massa_atomica": 112.41},
    {"simbolo": "In", "nome": "Índio", "numero_atomico": 49, "massa_atomica": 114.82},
    {"simbolo": "Sn", "nome": "Estanho", "numero_atomico": 50, "massa_atomica": 118.71},
    {"simbolo": "Sb", "nome": "Antimônio", "numero_atomico": 51, "massa_atomica": 121.76},
    {"simbolo": "Te", "nome": "Telúrio", "numero_atomico": 52, "massa_atomica": 127.60},
    {"simbolo": "I", "nome": "Iodo", "numero_atomico": 53, "massa_atomica": 126.90},
    {"simbolo": "Xe", "nome": "Xenônio", "numero_atomico": 54, "massa_atomica": 131.29},
    {"simbolo": "Cs", "nome": "Césio", "numero_atomico": 55, "massa_atomica": 132.91},
    {"simbolo": "Ba", "nome": "Bário", "numero_atomico": 56, "massa_atomica": 137.33},
    {"simbolo": "La", "nome": "Lantânio", "numero_atomico": 57, "massa_atomica": 138.91},
    {"simbolo": "Ce", "nome": "Cério", "numero_atomico": 58, "massa_atomica": 140.12},
    {"simbolo": "Pr", "nome": "Praseodímio", "numero_atomico": 59, "massa_atomica": 140.91},
    {"simbolo": "Nd", "nome": "Neodímio", "numero_atomico": 60, "massa_atomica": 144.24},
    {"simbolo": "Pm", "nome": "Promécio", "numero_atomico": 61, "massa_atomica": 145.00},
    {"simbolo": "Sm", "nome": "Samário", "numero_atomico": 62, "massa_atomica": 150.36},
    {"simbolo": "Eu", "nome": "Euprósio", "numero_atomico": 63, "massa_atomica": 151.98},
    {"simbolo": "Gd", "nome": "Gadolínio", "numero_atomico": 64, "massa_atomica": 157.25},
    {"simbolo": "Tb", "nome": "Térbio", "numero_atomico": 65, "massa_atomica": 158.93},
    {"simbolo": "Dy", "nome": "Dysprósio", "numero_atomico": 66, "massa_atomica": 162.50},
    {"simbolo": "Ho", "nome": "Hólmio", "numero_atomico": 67, "massa_atomica": 164.93},
    {"simbolo": "Er", "nome": "Érbio", "numero_atomico": 68, "massa_atomica": 167.26},
    {"simbolo": "Tm", "nome": "Túlio", "numero_atomico": 69, "massa_atomica": 168.93},
    {"simbolo": "Yb", "nome": "Ítterbium", "numero_atomico": 70, "massa_atomica": 173.04},
    {"simbolo": "Lu", "nome": "Lutécio", "numero_atomico": 71, "massa_atomica": 175.00},
    {"simbolo": "Hf", "nome": "Háfnio", "numero_atomico": 72, "massa_atomica": 178.49},
    {"simbolo": "Ta", "nome": "Tântalo", "numero_atomico": 73, "massa_atomica": 180.95},
    {"simbolo": "W", "nome": "Wolframio", "numero_atomico": 74, "massa_atomica": 183.84},
    {"simbolo": "Re", "nome": "Rênio", "numero_atomico": 75, "massa_atomica": 186.21},
    {"simbolo": "Os", "nome": "Ósmio", "numero_atomico": 76, "massa_atomica": 190.23},
    {"simbolo": "Ir", "nome": "Irídio", "numero_atomico": 77, "massa_atomica": 192.22},
    {"simbolo": "Pt", "nome": "Platina", "numero_atomico": 78, "massa_atomica": 195.08},
    {"simbolo": "Au", "nome": "Ouro", "numero_atomico": 79, "massa_atomica": 196.97},
    {"simbolo": "Hg", "nome": "Mercúrio", "numero_atomico": 80, "massa_atomica": 200.59},
    {"simbolo": "Tl", "nome": "Tálio", "numero_atomico": 81, "massa_atomica": 204.38},
    {"simbolo": "Pb", "nome": "Chumbo", "numero_atomico": 82, "massa_atomica": 207.2},
    {"simbolo": "Bi", "nome": "Bismuto", "numero_atomico": 83, "massa_atomica": 208.98},
    {"simbolo": "Po", "nome": "Polônio", "numero_atomico": 84, "massa_atomica": 209.00},
    {"simbolo": "At", "nome": "Astato", "numero_atomico": 85, "massa_atomica": 210.00},
    {"simbolo": "Rn", "nome": "Radônio", "numero_atomico": 86, "massa_atomica": 222.00},
    {"simbolo": "Fr", "nome": "Frâncio", "numero_atomico": 87, "massa_atomica": 223.00},
    {"simbolo": "Ra", "nome": "Radônio", "numero_atomico": 88, "massa_atomica": 226.00},
    {"simbolo": "Ac", "nome": "Actínio", "numero_atomico": 89, "massa_atomica": 227.00},
    {"simbolo": "Th", "nome": "Tório", "numero_atomico": 90, "massa_atomica": 232.04},
    {"simbolo": "Pa", "nome": "Protactínio", "numero_atomico": 91, "massa_atomica": 231.04},
    {"simbolo": "U", "nome": "Urânio", "numero_atomico": 92, "massa_atomica": 238.03},
    {"simbolo": "Np", "nome": "Neptúnio", "numero_atomico": 93, "massa_atomica": 237.00},
    {"simbolo": "Pu", "nome": "Plutônio", "numero_atomico": 94, "massa_atomica": 244.00},
    {"simbolo": "Am", "nome": "Amerício", "numero_atomico": 95, "massa_atomica": 243.00},
    {"simbolo": "Cm", "nome": "Cúrio", "numero_atomico": 96, "massa_atomica": 247.00},
    {"simbolo": "Bk", "nome": "Berquélio", "numero_atomico": 97, "massa_atomica": 247.00},
    {"simbolo": "Cf", "nome": "Califórnio", "numero_atomico": 98, "massa_atomica": 251.00},
    {"simbolo": "Es", "nome": "Einstênio", "numero_atomico": 99, "massa_atomica": 252.00},
    {"simbolo": "Fm", "nome": "Fermium", "numero_atomico": 100, "massa_atomica": 257.00},
    {"simbolo": "Md", "nome": "Mendelévio", "numero_atomico": 101, "massa_atomica": 258.00},
    {"simbolo": "No", "nome": "Nobelium", "numero_atomico": 102, "massa_atomica": 259.00},
    {"simbolo": "Lr", "nome": "Laurêncio", "numero_atomico": 103, "massa_atomica": 262.00},
    {"simbolo": "Rf", "nome": "Rutherfórdio", "numero_atomico": 104, "massa_atomica": 267.00},
    {"simbolo": "Db", "nome": "Dúbnio", "numero_atomico": 105, "massa_atomica": 270.00},
    {"simbolo": "Sg", "nome": "Seabórgio", "numero_atomico": 106, "massa_atomica": 271.00},
    {"simbolo": "Bh", "nome": "Bohrium", "numero_atomico": 107, "massa_atomica": 270.00},
    {"simbolo": "Hs", "nome": "Hássio", "numero_atomico": 108, "massa_atomica": 277.00},
    {"simbolo": "Mt", "nome": "Meitnério", "numero_atomico": 109, "massa_atomica": 276.00},
    {"simbolo": "Ds", "nome": "Darmstádio", "numero_atomico": 110, "massa_atomica": 281.00},
    {"simbolo": "Rg", "nome": "Roentgênio", "numero_atomico": 111, "massa_atomica": 280.00},
    {"simbolo": "Cn", "nome": "Copernício", "numero_atomico": 112, "massa_atomica": 285.00},
    {"simbolo": "Uut", "nome": "Ununtrium", "numero_atomico": 113, "massa_atomica": 284.00},
    {"simbolo": "Fl", "nome": "Fleróvio", "numero_atomico": 114, "massa_atomica": 289.00},
    {"simbolo": "Uup", "nome": "Ununpêntio", "numero_atomico": 115, "massa_atomica": 288.00},
    {"simbolo": "Lv", "nome": "Livermório", "numero_atomico": 116, "massa_atomica": 293.00},
    {"simbolo": "Uus", "nome": "Ununséptio", "numero_atomico": 117, "massa_atomica": 294.00},
    {"simbolo": "Uuo", "nome": "Ununoctium", "numero_atomico": 118, "massa_atomica": 294.00}
]

def buscar_elemento(busca):
    for elemento in elementos:
        if busca.lower() in elemento["nome"].lower() or busca.lower() == elemento["simbolo"].lower() or busca == str(elemento["numero_atomico"]):
            return elemento
    return None

print("==== Calculadora de Impressão da Tabela Periódica ====")
print("Você pode buscar por nome, símbolo ou número atômico")
busca = input("Digite o que deseja buscar: ")

resultado = buscar_elemento(busca)

if resultado:
    print("\n=== Resultado encontrado ===")
    print(f"Nome: {resultado['nome']}")
    print(f"Símbolo: {resultado['simbolo']}")
    print(f"Número atômico: {resultado['numero_atomico']}")
    print(f"Massa atômica: {resultado['massa_atomica']}")
else:
    print("\nElemento não encontrado. Verifique a entrada e tente novamente.")
